[package]
name = "pinocchio-fundraiser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
bpf-entrypoint = []

[dependencies]
pinocchio = "0.11"
pinocchio-system = "0.6"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }

[dev-dependencies]
mollusk-svm = "0.14.0"
solana-account = "4.3.1"
solana-instruction = "3.4.0"
solana-program-error = "3.0.1"
solana-pubkey = { version = "4.2.0", features = ["curve25519"] }
solana-sdk-ids = "3.1.0"
